### ISSUE TITLE
Wiki link generates 404 in README.md

### ISSUE THREAD

**Issue by mariannemyers** [marklogic-community/marklogic-mule-connector#31]
This link generates a 404 for me.  

https://github.com/marklogic-community/marklogic-mule-connector/blob/development/Wiki

Perhaps you could also add a link to the correct docs in the "header" area where it currently just says "MarkLogic Mulesoft Connector"?

**Comment by wattsferry** [comment]
Thanks, and good catch, Marianne.  I'll add the cleaned up link to the Wiki in the header, and will get the README.md fixed for the next release, too.

**Comment by wattsferry** [comment]
I just went ahead an did a hotfix.  Thanks.

**Comment by mariannemyers** [comment]
Thanks @wattsferry!
